
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace EPPlusTUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class EPPlusTUI : Terminal.Gui.Window {
        
        private Terminal.Gui.Label excelFileLabel;
        
        private Terminal.Gui.TextField excelFileField;
        
        private Terminal.Gui.Label scanDirLabel;
        
        private Terminal.Gui.TextField scanDirField;
        
        private Terminal.Gui.Label dLabel;
        
        private Terminal.Gui.TextField dField;
        
        private Terminal.Gui.Button generateButton;
        
        private Terminal.Gui.Label errorLabel;
        
        private void InitializeComponent() {
            this.errorLabel = new Terminal.Gui.Label();
            this.generateButton = new Terminal.Gui.Button();
            this.dField = new Terminal.Gui.TextField();
            this.dLabel = new Terminal.Gui.Label();
            this.scanDirField = new Terminal.Gui.TextField();
            this.scanDirLabel = new Terminal.Gui.Label();
            this.excelFileField = new Terminal.Gui.TextField();
            this.excelFileLabel = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "EPPlusTUI";
            this.excelFileLabel.Width = 7;
            this.excelFileLabel.Height = 1;
            this.excelFileLabel.X = 20;
            this.excelFileLabel.Y = 1;
            this.excelFileLabel.Visible = true;
            this.excelFileLabel.Data = "excelFileLabel";
            this.excelFileLabel.Text = "Ścieżka zapisu";
            this.excelFileLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.excelFileLabel);
            this.excelFileField.Width = Dim.Fill(14);
            this.excelFileField.Height = 3;
            this.excelFileField.X = 51;
            this.excelFileField.Y = 1;
            this.excelFileField.Visible = true;
            this.excelFileField.Secret = false;
            this.excelFileField.Data = "excelFileField";
            this.excelFileField.Text = "scanDir.xlsx";
            this.excelFileField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.excelFileField);
            this.scanDirLabel.Width = 3;
            this.scanDirLabel.Height = 1;
            this.scanDirLabel.X = 20;
            this.scanDirLabel.Y = 3;
            this.scanDirLabel.Visible = true;
            this.scanDirLabel.Data = "scanDirLabel";
            this.scanDirLabel.Text = "Ścieżka do przeszukania";
            this.scanDirLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.scanDirLabel);
            this.scanDirField.Width = Dim.Fill(14);
            this.scanDirField.Height = 3;
            this.scanDirField.X = 51;
            this.scanDirField.Y = 3;
            this.scanDirField.Visible = true;
            this.scanDirField.Secret = false;
            this.scanDirField.Data = "scanDirField";
            this.scanDirField.Text = ".";
            this.scanDirField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.scanDirField);
            this.dLabel.Width = 3;
            this.dLabel.Height = 1;
            this.dLabel.X = 20;
            this.dLabel.Y = 5;
            this.dLabel.Visible = true;
            this.dLabel.Data = "dLabel";
            this.dLabel.Text = "Głębokość wyszukiwania";
            this.dLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.dLabel);
            this.dField.Width = Dim.Fill(14);
            this.dField.Height = 3;
            this.dField.X = 51;
            this.dField.Y = 5;
            this.dField.Visible = true;
            this.dField.Secret = false;
            this.dField.Data = "dField";
            this.dField.Text = "4";
            this.dField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.dField);
            this.generateButton.Width = 11;
            this.generateButton.Height = 1;
            this.generateButton.X = Pos.Center();
            this.generateButton.Y = 9;
            this.generateButton.Visible = true;
            this.generateButton.Data = "generateButton";
            this.generateButton.Text = "Generuj";
            this.generateButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.generateButton.IsDefault = false;
            this.Add(this.generateButton);
            this.errorLabel.Width = 12;
            this.errorLabel.Height = 1;
            this.errorLabel.X = 2;
            this.errorLabel.Y = 12;
            this.errorLabel.Visible = true;
            this.errorLabel.Data = "errorLabel";
            this.errorLabel.Text = "Info box";
            this.errorLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.errorLabel);
        }
    }
}
